# Dependencies python=3.6 cutadapt starcode pysam seaborn numpy matplotlib snakemake-minimal tqdm jupyter
channels:
  - conda-forge
  - defaults
  - r
  - bioconda
dependencies:
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - bcftools=1.9
  - bz2file=0.98
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.7
  - curl=7.64.1
  - cutadapt=2.3
  - cycler=0.10.0
  - datrie=0.7.1
  - dnaio=0.3
  - docutils=0.14
  - freetype=2.10.0
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - htslib=1.9
  - idna=2.8
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libcxx=8.0.0
  - libcxxabi=8.0.0
  - libdeflate=1.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.*
  - liblapack=3.8.0
  - libpng=1.6.37
  - libssh2=1.8.2
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - ncurses=6.1
  - numpy=1.16.4
  - openssl=1.1.1b
  - pandas=0.24.2
  - patsy=0.5.1
  - pigz=2.3.4
  - pip=19.1.1
  - psutil=5.6.3
  - pycparser=2.19
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyrsistent=0.15.2
  - pysam=0.15.2
  - pysocks=1.7.0
  - python=3.6.7
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1.1
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.22.0
  - samtools=1.9
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=41.0.1
  - six=1.12.0
  - smmap2=2.0.5
  - snakemake-minimal=5.5.0
  - sqlite=3.28.0
  - starcode=1.3
  - statsmodels=0.9.0
  - tk=8.6.9
  - tornado=6.0.2
  - tqdm=4.32.1
  - urllib3=1.24.3
  - umi_tools=1.0.0
  - wheel=0.33.4
  - wrapt=1.11.1
  - xopen=0.7.0
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
