# Whenever this file is updated, you need to run misc/condalock.sh `bash
# misc/condalock.sh` to create the environment.lock.yml file.
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - cutadapt
  - dnaio
  - jupyter
  - pandas
  - pigz
  - pysam
  - python=3.6
  - samtools
  - seaborn
  - starcode
  - tqdm
  - importlib_resources
  - snakemake-minimal
  - umi_tools
  - ruamel.yaml